spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true              # 콘솔에 쿼리 출력
    properties:
      hibernate:
        format_sql: true        # 쿼리 줄바꿈
        highlight_sql: true     # 쿼리에 색상을 입혀서 가독성 높임
        use_sql_comments: true  # 쿼리 옆에 어떤 JPQL인지 주석 달아줌

  jwt:
    secret: ${JWT_SECRET_KET}   # JWT 시크릿 키
    access-expiration: 6000000   # 1시간
    refresh-expiration: 604800000 # 7일