spring:
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-name: google
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
#            authorization-grant-type: authorization_code
#            scope:
#              - profile
#              - email
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            provider: naver # 네이버는 아래 provider에 등록한 이름을 참조해야 함

        # 네이버와 같은 커스텀 서비스 공급자 설정
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버 응답은 response 라는 키 안에 유저 정보가 들어있음